### PR TITLE
ceramic.lisp define-entry-point already finds the full binary pathnam…

### PR DESCRIPTION
**Pull request by jkordani**
…e before passing to start-process.  doing this again inside of start process results in a bad path being passed.  only tested on osx.  I imagine that error handling would also be desired here.  I wonder how this was working on other platforms....

### CODE REVIEW

**Comment by eudoxia0** [comment]
Why did you do that thing in the bundler where you don't copy the Electron directory?

**Comment by jkordani** [comment]
I'm sorry!!!! I didn't mean to make a pull request for this yet... I meant to only commit to my own fork...  I'm rather new to github.  you can close this out.

I commented out the electron copy due to issue 12.  But again, I didn't mean to make a pull request for this, just to track these in my own fork.

**Comment by eudoxia0** [comment]
Oh, that's fine. You just commit and I'll leave this up here and we'll review it once it's done?

**Comment by jkordani** [comment]
to clarify, I only meant to push the first commit...  I'll make a new pull request just for that.

**Comment by eudoxia0** [comment]
Right, ok.

**Comment by jkordani** [comment]
er,  can I edit this PR to remove the commits I don't want, or do I need to make a new PR?

**Comment by eudoxia0** [comment]
I think you can rewrite the PR history, but I know nothing about Git beyond simple branching. We should leave this one closed, and you open a new one when you're done.

**Pull request closed without merging**
