### PR TITLE
Electron 1.2.7 upgrade

### PR DESCRIPTION
**Pull request by mikeivanov**
I had to change a few things in order to get Ceramic work with the latest Electron.

### CODE REVIEW

**Comment by eudoxia0** [comment]
Yo, thanks. And I see you've added crash report functionality. Great!

Looks like you forgot to add `t/crashreporter.lisp` to the test system definition though, that's what's failing the test.

**Comment by mikeivanov** [comment]
It currently hangs at "(setf (ceramic.window:title win) new-title)" in t/window.lisp, do you have any ideas why?
Of course, it works just fine locally.

**Comment by eudoxia0** [comment]
I suspect it's waiting forever for events that aren't being sent. Maybe related to changing `localhost` to `127.0.0.1`?

**Comment by mikeivanov** [comment]
Changed back to localhost - no effect. Also, all other tests pass, so only this event is not being sent.

**Comment by eudoxia0** [comment]
Oh, fuck it, I'm gonna merge and see what comes about.

**Pull request merged**
